volumes:
  db-data:
  pgbackrest-log:

services:
  dblab:
    image: postgresai/dblab-server:4.0.4
    restart: unless-stopped
    privileged: true
    ports:
      - 2345:2345
    environment:
      DOCKER_API_VERSION: ${DOCKER_API_VERSION}
      PGPASSWORD: ${DB_PASSWORD}
      DLE_VERIFICATION_TOKEN: ${DBLAB_VERIFICATION_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/dblab:/var/lib/dblab:rshared
      - ${HOME}/.dblab/engine/configs:/home/dblab/configs
      - ./dblab-server.yml:/home/dblab/configs/server.yml:ro
      - ${HOME}/.dblab/engine/meta:/home/dblab/meta
      - ${HOME}/.dblab/engine/logs:/home/dblab/logs
      - /sys/kernel/debug:/sys/kernel/debug:rw
      - /lib/modules:/lib/modules:ro
      - /proc:/host_proc:ro

  db:
    image: ghcr.io/kvdomingo/postgresql-pig:18
    restart: unless-stopped
    shm_size: 1g
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGBACKREST_REPO1_S3_KEY: ${AWS_ACCESS_KEY_ID}
      PGBACKREST_REPO1_S3_KEY_SECRET: ${AWS_SECRET_ACCESS_KEY}
      PGBACKREST_REPO1_S3_REGION: ap-southeast-1
      PGBACKREST_REPO2_S3_KEY: ${BACKBLAZE_KEY_ID}
      PGBACKREST_REPO2_S3_KEY_SECRET: ${BACKBLAZE_APP_KEY}
      PGBACKREST_REPO2_S3_REGION: us-west-002
      PGBACKREST_REPO2_S3_ENDPOINT: s3.us-west-002.backblazeb2.com
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql
      - ./entrypoint.sh:/entrypoint.sh:ro
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./pgbackrest.conf:/etc/pgbackrest/pgbackrest.conf:ro
      - pgbackrest-log:/var/log/pgbackrest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 10s
      interval: 20s
      timeout: 5s
      retries: 3

  backup:
    image: ghcr.io/kvdomingo/postgresql-pig:18
    restart: unless-stopped
    shm_size: 1g
    entrypoint: supercronic
    command:
      - /etc/pgbackrest/crontab
    environment:
      PGBACKREST_REPO1_S3_KEY: ${AWS_ACCESS_KEY_ID}
      PGBACKREST_REPO1_S3_KEY_SECRET: ${AWS_SECRET_ACCESS_KEY}
      PGBACKREST_REPO1_S3_REGION: ap-southeast-1
      PGBACKREST_REPO2_S3_KEY: ${BACKBLAZE_KEY_ID}
      PGBACKREST_REPO2_S3_KEY_SECRET: ${BACKBLAZE_APP_KEY}
      PGBACKREST_REPO2_S3_REGION: us-west-002
      PGBACKREST_REPO2_S3_ENDPOINT: s3.us-west-002.backblazeb2.com
    volumes:
      - db-data:/var/lib/postgresql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./pgbackrest.conf:/etc/pgbackrest/pgbackrest.conf:ro
      - ./pgbackrest-crontab:/etc/pgbackrest/crontab:ro
      - pgbackrest-log:/var/log/pgbackrest

  supavisor:
    image: supabase/supavisor:2.7.4
    restart: unless-stopped
    environment:
      PORT: 4000
      PROXY_PORT_SESSION: 5433
      PROXY_PORT_TRANSACTION: 6543
      DATABASE_URL: "ecto://postgres:${DB_PASSWORD}@db:5432/postgres"
      CLUSTER_POSTGRES: true
      SECRET_KEY_BASE: ${POOLER_SECRET_KEY_BASE}
      VAULT_ENC_KEY: ${POOLER_VAULT_ENC_KEY}
      API_JWT_SECRET: ${POOLER_API_JWT_SECRET}
      METRICS_JWT_SECRET: ${POOLER_METRICS_JWT_SECRET}
      REGION: "local"
      ERL_AFLAGS: -proto_dist inet_tcp
      POOLER_TENANT_ID: kvdstudio
      POOLER_DEFAULT_POOL_SIZE: 20
      POOLER_MAX_CLIENT_CONN: 100
      POOLER_POOL_MODE: transaction
    command:  sh -c "/app/bin/migrate && /app/bin/server"
    ports:
      - 4000:4000
      - 5433:5433
      - 6543:6543
    depends_on:
      db:
        condition: service_started
