volumes:
  db-data:

services:
  db:
    image: ghcr.io/kvdomingo/postgresql-pig:17
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro

  backup:
    image: offen/docker-volume-backup:v2
    restart: unless-stopped
    environment:
      AWS_S3_BUCKET_NAME: lab-srv-pg-01-backups
      AWS_S3_PATH: backup/db-primary
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      BACKUP_CRON_EXPRESSION: "0 0 * * *"
      BACKUP_COMPRESSION: zst
      BACKUP_FILENAME: "backup-%Y%m%dT%H%M%SZ.{{ .Extension }}"
      BACKUP_FILENAME_EXPAND: true
      BACKUP_FROM_SNAPSHOT: true
    volumes:
      - db-data:/backup/db-primary:ro

  supavisor:
    image: supabase/supavisor:2.7.4
    restart: unless-stopped
    environment:
      PORT: 4000
      PROXY_PORT_SESSION: 5433
      PROXY_PORT_TRANSACTION: 6543
      DATABASE_URL: "ecto://postgres:${DB_PASSWORD}@db:5432/postgres"
      CLUSTER_POSTGRES: true
      SECRET_KEY_BASE: ${POOLER_SECRET_KEY_BASE}
      VAULT_ENC_KEY: ${POOLER_VAULT_ENC_KEY}
      API_JWT_SECRET: ${POOLER_API_JWT_SECRET}
      METRICS_JWT_SECRET: ${POOLER_METRICS_JWT_SECRET}
      REGION: "local"
      ERL_AFLAGS: -proto_dist inet_tcp
      POOLER_TENANT_ID: kvdstudio
      POOLER_DEFAULT_POOL_SIZE: 20
      POOLER_MAX_CLIENT_CONN: 100
      POOLER_POOL_MODE: transaction
    command:  sh -c "/app/bin/migrate && /app/bin/server"
    ports:
      - 4000:4000
      - 5433:5433
      - 6543:6543
    depends_on:
      - db
