version: '3'

env:
  COMMIT_SHA:
    sh: git rev-parse --short HEAD
  IMAGE_NAME: ghcr.io/kvdomingo/postgresql-pig

tasks:
  default:
    cmd: bake

  init:
    desc: Initial setup
    cmds:
      - pip install -U pre-commit
      - pre-commit install

  bake:
    desc: Bake Docker image
    cmd: docker buildx bake -f docker-bake.hcl
