version: "3"

env:
  COMMIT_SHA:
    sh: git rev-parse --short HEAD
  IMAGE_NAME: ghcr.io/kvdomingo/postgresql-pig

tasks:
  default:
    cmd:
      task: bake

  init:
    desc: Initial setup
    cmds:
      - pip install -U pre-commit
      - pre-commit install

  bake:
    desc: Bake Docker image
    cmd: docker buildx bake -f docker-bake.hcl

  tf-init:
    desc: Initialize Terraform
    cmd: infisical run -- terraform init {{ .CLI_ARGS }}

  tf-plan:
    desc: Plan Terraform resources
    cmd: infisical run -- terraform plan -out .tfplan {{ .CLI_ARGS }}

  tf-apply:
    desc: Apply Terraform plan
    cmd: infisical run -- terraform apply .tfplan {{ .CLI_ARGS }}
