name: '[Pipeline] Build Docker images'

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: build-${{ inputs.version }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  build:
    uses: ./.github/workflows/common-build.yaml
    secrets: inherit
    strategy:
      matrix:
        version: [ 15, 16, 17 ]
    with:
      version: ${{ matrix.version }}
