name: '[Pipeline] Build Docker images'

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: build-${{ inputs.version }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  build-15:
    uses: ./.github/workflows/common-build.yaml
    secrets: inherit
    with:
      version: 15

  build-16:
    uses: ./.github/workflows/common-build.yaml
    secrets: inherit
    with:
      version: 16

  build-17:
    uses: ./.github/workflows/common-build.yaml
    secrets: inherit
    with:
      version: 17
