name: '[Component] Build Docker image'

on:
  workflow_call:
    inputs:
      version:
        type: number
        required: true
        description: PostgreSQL version
  workflow_dispatch:
    inputs:
      version:
        type: number
        required: true
        description: PostgreSQL version

jobs:
  build:
    name: Build PostgreSQL ${{ inputs.version }} with Pig CLI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: docker/setup-buildx-action@v3
        name: Setup Docker Buildx

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/postgresql-pig
          tags: |
            type=sha
            type=raw,value=${{ inputs.version }}-bitnami

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ${{ inputs.version }}.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
